Fixed dangerous ctor/dtor symbols
Ctors and dtors were using the wrong symbols. At best, compilation failed with 'undefined reference to' errors. However, this issue may lead to extremely dangerous situations and crashes due to the way ctor/dtor symbols are defined:
D0 for deleting dtor, D1 for standard dtor, D2 for class inheritance dtor, C1 for standard ctor, C2 for class inheritance ctor
D1/D2 and C1/C2 were swapped, which may have led to vtable accesses inside a virtual dtor, therefore either creating an infinite loop, weird compiler errors or missing dtor invokation.